token:
  secret:
    key: bc0e1123830be23b99e69b46d808c6a6f9249ba900e4c38558fca57540851aee

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

site:
  aes256:
    secret:
      key: xQ8fBz8dP7TgH9JcVnX5oR1kS2zA7W41


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TravelMate
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always

server:
  api:
    prefix: /api/v1  # API 프리픽스 설정
