token:
    secret:
      key: bc0e1123830be23b99e69b46d808c6a6f9249ba900e4c38558fca57540851aee

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TravelMate
    username: root
    password: # Enter Password
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always  # 서버 시작 시 SQL 스크립트를 실행하도록 설정
      schema-locations: classpath:/TABLE/schema.sql
      data-locations: classpath:/TABLE/data.sql

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL에 맞는 Dialect 설정
