token:
    secret:
      key: bc0e1123830be23b99e69b46d808c6a6f9249ba900e4c38558fca57540851aee

site:
  aes256:
    secret:
      key: xQ8fBz8dP7TgH9JcVnX5oR1kS2zA7W41


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TravelMate
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always  # 서버 시작 시 SQL 스크립트를 실행하도록 설정
      schema-locations: classpath:/TABLE/schema.sql
      data-locations: classpath:/TABLE/data.sql

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL에 맞는 Dialect 설정
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql:
                BasicBinder: TRACE

server:
  api:
    prefix: /api/v1  # API 프리픽스 설정